version: "3.0"

services:
  api:
    build: .
    container_name: app_entrega23
    ports:
      # local --> contenedor
      - 6000:6000
    
    restart: always
    
    # opcional ya que ayuda a desarrollar con el docker compose ejecutandose
    volumes:
      - .:/usr/src/app

volumes:
  entrega23:
